### ISSUE TITLE
Add kafka producer and consumer options

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#194]
- [ ] Add producer and consumer options in datasource. These options can be specified at workflow level also.
producer:
   options:
consumer:
   options:

- [ ] Extend client options also in datasources.

**Comment by arunsingh** [comment]
https://kafka.js.org/docs/consuming#options    We can add options for Producer, consumer and client by referring shared documentation link, Refer consumer  function in this Snippet https://github.com/godspeedsystems/gs-node-service/blob/master/src/kafka/index.ts#L84
