### ISSUE TITLE
Import all the cloud SDKs (AWS, Google, etc.,)

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#282]
Expose the SDKs as datasource and corresponding functions like

- com.gs.aws
- com.gs.azure
- com.gs.gcloud

Datasource types:

- type: aws
- type: azure
- type: gcloud

**Comment by arunsingh** [comment]
Implement Azure,  gcloud SDKs using extensible data sources. https://docs.godspeed.systems/docs/microservices/datasources/extensible-datasources.

Once these are implemented, we can add in Godspeed documentation in same datasources extensible as examples https://docs.godspeed.systems/docs/microservices/datasources/extensible-datasources
