### ISSUE TITLE
vscode JS/TS/Coffee script check

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#411]
- Compile time check of JS/TS inline scripting
- yaml has code blocks. in the extension package you define code blocks
- there is existing lang server for js cs
- setup lang server and redirect files to that server. 
- create virtual documents of inline js cs files for lang server
- the lang server will return errors and highlights and steps to format js
- apply this to the inline js thru vscode

highlighting is already done thru manifest file.

there is a lang server also in lang tools branch of language tools repo. branch needs merge

document the implementation so that any dev can pick it up

**Comment by xCodeMuse** [comment]
@ashutoshmindgrep I dont find any lang server/ lang tools branch which needs to be merged.

**Comment by ashutoshmindgrep** [comment]
Sorry I forgot to push the branch. Now pushed. You can access it here.
[lang server branch](https://github.com/godspeedsystems/language-tools/tree/feat/language-server)
