### ISSUE TITLE
Make build time shorter

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#446]
Build time has been significantly improved benchmarking result

https://siddocumenting.notion.site/Godspeed-Build-time-Benchmarking-7a6a6306e1bc4b90be5c21162fbc94c0?pvs=4

**Comment by arunsingh** [comment]
Build should also generate the prisma client

**Comment by siddarthvader** [comment]
Benchmarking document.


https://siddocumenting.notion.site/Godspeed-Build-time-Benchmarking-7a6a6306e1bc4b90be5c21162fbc94c0?pvs=4

**Comment by mastersilv3r** [comment]
To put a blog post about how we improved this. Connect with Siddharth our intern.
