### ISSUE TITLE
Documentation of default setup of databases and accessing them through respective admin panels

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#461]

**Comment by mastersilv3r** [comment]
- [ ] default user password url port
- [ ] Add documentation on how to connect to mongodb and postgresdb using clients(compass, pgadmin, etc.,) on local system

**Comment by Mohit-Sharma1** [comment]
Just add the default user url for the any integration is available in the docker compose

**Comment by Srihari628** [comment]
Please check this.. if this is ok then i will add it to documentation

**Comment by Srihari628** [comment]
made changes to the documentation raised a PR kindly review it

https://github.com/godspeedsystems/gs_doc/pull/36
