### ISSUE TITLE
Bug: JWT token signature matching issue

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#475]
as long as the sceret key is correct any kind of payload is getting passed.

**Comment by arunsingh** [comment]
@xCodeMuse Surya to follow up with Ashutosh

**Comment by xCodeMuse** [comment]
As long as the sceret key is correct any kind of payload is getting passed.

My findings

-  Thats not the case, if you pass issuer or audience value and in the token the value is set different than the payload, the response will be `Unauthorized.` 
- ![Image](https://github.com/godspeedsystems/gs-node-service/assets/32449199/1dad0bc0-4a5b-47e7-b05b-eeb201107ba9)
- the only payload properties which are considered by the passport auth are as mentioned above in the attached image.
