### ISSUE TITLE
Add event sources in gs_service

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#492]
for custom datasource, route regex naming convention changed from hardcoded 2 dots and 3 values. Now it is changed to allow flexibility to individual datasource

old way
topic.datasourname.groupid 
 new way
no restriction on dots or values. But, second one will always be datasource name. subscribe method of the client object of the datasource needs to handle this.

test that old integrations are working

- [x] kafka @ashu
- [x] redis @ashu
- [x] salesforce @kushal

**Comment by arunsingh** [comment]
@gnani1226 to follow up with Samba and Kushal to test this with salesforce or Rabbit MQ

**Comment by arunsingh** [comment]
I have worked on this ticket , Step, 1,2 completed, and Spent considerable time of the day fixing new CLI vs Old CLI in my local system. However, API is working now, S3 is under progress, have written API to convert RabbitMQ data source to event source, have to integrate this peace & test end to end functionality.

**Comment by mastersilv3r** [comment]
Please share the code done so far. The Rabbitmq datasource yaml and its code. Put the fles here and we would like to test it.

**Comment by mastersilv3r** [comment]
Please share the latest code with Sambna.

**Comment by arunsingh** [comment]
datasources.yaml

 type: rabbitmq
loadFn: com.rabbitmq.loader
executeFn: com.rabbitmq.execute
#client_url: http://localhost:15672/
client_url: amqp://guest:guest@localhost:5672
client_id: rabbitmq-1

**Comment by arunsingh** [comment]
loader.ts

const amqplib = require('amqplib/callback_api');
//const http = require('http');


module.exports = async function (args: { [key: string]: any; }, callback) {
  const conn = await amqplib.connect(args.client_url);
  //const conn = await http.get(args.client_url); 
  console.log('conn')
  const ds = {
    ...args, 
    client: conn
  };
  return ds;
}

**Comment by mastersilv3r** [comment]
Creating a separate repository for code of differente integrations like Rabbit MQ as datasource and event source.

**Comment by mastersilv3r** [comment]
test that old integrations are working

- [ ] kafka
- [ ] redis

**Comment by Mohit-Sharma1** [comment]
Test with MQ
