### ISSUE TITLE
Spec for core module and integration system

### ISSUE THREAD

**Issue by arunsingh** [godspeedsystems/gs-node-service#507]
A spec of how product sdk will work across languages in a unified way
a core module plus integration system to add plugins
for both brown field and green field projects
unified interfaces decouple with web server ex express springboot
cli
a way to set up in existing project or create a new project
for existing project, add docker files helm charts ci/cd control plane flow, make it remote comtainerized. build clean dev commans..cli can setup dockerized services or native services…
give dev list of pre reqs of what he needs to install dockerized or native services.. refer heroku proc files.. for remote containerization there is an open spec which most ides support. 

support writing code in native language thru annotations interfaces etc

allow calling yaml workflows from functions

this shud work in all IDEs

**Comment by ashutoshmindgrep** [comment]
Can someone point me to the work done by @gurjotmindgrep.

**Comment by gurjotmindgrep** [comment]
Here is that epic: [Import Godspeed projects as npm packages in other projects#351](https://github.com/godspeedsystems/gs-node-service/issues/351)
It has various issues linked and the progress.

**Comment by ashutoshmindgrep** [comment]
For plugins research done by @gurjotmindgrep refer #351

**Comment by mastersilv3r** [comment]
lets tighthen this and close. need remaining interfaces defined.

**Comment by mastersilv3r** [comment]
support for native language code also instead of yaml only..

**Comment by siddarthvader** [comment]
updated spec and added more details about core, interfaces, sdk, plugin etc.
