### ISSUE TITLE
Getting error while doing npm install if we remove existing node_modules and package-lock.json from gs_service

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#547]
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: mindgrep@1.0.15
npm ERR! Found: @opentelemetry/api@1.4.1
npm ERR! node_modules/@opentelemetry/api
npm ERR!   @opentelemetry/api@"^1.1.0" from the root project
npm ERR!   peer @opentelemetry/api@">=1.0.0 <1.5.0" from @opentelemetry/core@1.12.0
npm ERR!   node_modules/@opentelemetry/core
npm ERR!     @opentelemetry/core@"^1.5.0" from the root project
npm ERR!     @opentelemetry/core@"^1.0.0" from @opentelemetry/instrumentation-express@0.30.0
npm ERR!     node_modules/@opentelemetry/instrumentation-express
npm ERR!       @opentelemetry/instrumentation-express@"^0.30.0" from the root project
npm ERR!   6 more (@opentelemetry/exporter-metrics-otlp-grpc, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @opentelemetry/sdk-node@"^0.31.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @opentelemetry/api@1.1.0
npm ERR! node_modules/@opentelemetry/api
npm ERR!   peer @opentelemetry/api@">=1.0.0 <1.2.0" from @opentelemetry/sdk-node@0.31.0
npm ERR!   node_modules/@opentelemetry/sdk-node
npm ERR!     @opentelemetry/sdk-node@"^0.31.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/node/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-05-05T10_01_42_126Z-debug-0.log`

**Comment by ashutoshmindgrep** [comment]
@xCodeMuse Can you confirm IF you faced the same issue?
