### ISSUE TITLE
Use pino-http in place of express-pino-logger as it is deprecated

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#548]
During `npm install` in gs_service, getting warning that use pino-http instead of 'express-pino-logger'

shud be drop in replacement and requires testing for backward compatibility’s

**Comment by Mohit-Sharma1** [comment]
should be able to see the logs in the output while test

**Comment by xCodeMuse** [comment]
@Srihari628 PR already merged in Dev branch
**use** it for testing.

**Comment by Srihari628** [comment]
@xCodeMuse sir i tested it it is working fine and able to see the logs in the output
