### ISSUE TITLE
Update File upload feature for arrayBuf and stream type

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#551]
- [ ] For long files, we should use type as stream which works asynchronously.
- [ ] For shot files, if synchronous mechanism is required then arrayBuffer can be used as type so that file content is downloaded, saved in a file in local then the local file can be read.

**Comment by mastersilv3r** [comment]
Please ask Gurjot

**Comment by arunsingh** [comment]
We had the conversation, As per Gurjot input she will do it whenever she joins back. For now, there is some dependency while Gurjot is implemented at Pinelabs. She have idea how to implement this.
