### ISSUE TITLE
Latency issue in Pinelabs services LI and LI wrapper

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#561]
**Issue Description:**
Latency Issue on LI and LI wrapper services in Production.

**Analysis:**
During multiple debugging sessions, it was found that event loop was taking time along with CPU hikes whenever the issue was observed. To identify the root cause, we did benchmarking on these services and found an issue which was taking most of the CPU time.

**Root Cause:**
Compilation of inline scripting during runtime in a specific scenario where the arguments to the task are of type object. For example, the following workflow:

![Image](https://github.com/godspeedsystems/gs-node-service/assets/103424952/8675e7fa-52ae-40cb-bf4a-aa9c90419a83)

**Resolution:**
The compilation of script is moved to the loadtime instead of runtime.

**Benchmarking:**
https://docs.google.com/spreadsheets/d/1FnkunuEz3g6qGYSsaoDxwdOeKw1eYTxVTsgWD5OLzU4/edit?usp=sharing

To simulate the behaviour, 
We are calling two endpoints of LI:

- Get SOA: http://localhost:3000/lending/li/api/v1/loan-application/LD10135/loan-schedule?loan_number=2338

- Get status: http://localhost:3000/lending/li/api/v1/loan-application/LD9404/status

These endpoints call LI wrapper service. Hardcoded response is sent back LI to simulate the lender api response.

**Comment by arunsingh** [comment]
Part of Upcoming release 1.0.30
