### ISSUE TITLE
Getting error "Can not execute the operation on ended span" in com.gs.datastore

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#566]
Getting this error in logs when load is executed on LI wrapper service without DB task:

```
Can not execute the operation on ended Span {traceId: adace0e49154aaaa7d6f428314280bf0, spanId: 2c634a8ae3d6c3b7}
Can not execute the operation on ended Span {traceId: adace0e49154aaaa7d6f428314280bf0, spanId: 2c634a8ae3d6c3b7}
You can only call end() on a span once.
```

**Comment by arunsingh** [comment]
- follow up with Gurjot

**Comment by arunsingh** [comment]
The issue , Getting this error in logs when the load is executed on LI wrapper service without DB task: This was observed during load testing only and not seen frequently.


@gurjotmindgrep have done some code refactoring w.r.t span in this PR https://github.com/godspeedsystems/gs-node-service/issues/577 that might resolve this issue but it needs to be checked with load testing.
