### ISSUE TITLE
Do profiling of pino test with simple express app and godspeed app

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#574]
1. Express app - In express app, add pino log and do the various test with and without OTEL. The test case includes calling an api which executes a for loop 1000 times, does the logging and return response.
2. Godspeed app - The test includes calling an event which calls a workflow yaml with one task. The yaml workflow is calling custom js function which executes a for loop 1000 times, does the logging and return response.

**Comment by gurjotmindgrep** [comment]
Here is the report of profiling with express app and Godspeed app: https://docs.google.com/spreadsheets/d/1p78NvWAEPrRTUAkPkyASF5xqMI4wuyIR0qd0cxdX8Ug/edit?usp=sharing

**Express App:** 
- Repo: https://github.com/godspeedsystems/express-profiling-app
- Endpoint: /pino-test

**Godspeed app:** 

- Repo: https://github.com/godspeedsystems/godspeed-profiling-app
- Endpoint: /pino-test

**Comment by arunsingh** [comment]
Follow up on progress
