### ISSUE TITLE
com.gs.datastore: Not able to execute prisma transaction and raw queries

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#577]
https://github.com/godspeedsystems/gs-node-service/pull/578 - Prisma transaction queries are implemented in this PR & raw queries are still pending?

Step 1.  In native function `com.gs.datastore prisma` queries transaction[https://github.com/godspeedsystems/gs-node-service/pull/578] and raw queries are not working in gs_service
Step 2. To test this transaction PR.
Step 3. Refer this https://github.com/godspeedsystems/gs-node-service/pull/578 to implement PRISMA raw queries as well.

**Comment by arunsingh** [comment]
To ask for @gurjotmindgrep time & clarify about this issue. & note down on tickets.

**Comment by arunsingh** [comment]
We can keep it in backlog.
