### ISSUE TITLE
Audit Log [requirement from pineLabs] [Datasource hooks]]

### ISSUE THREAD

**Issue by xCodeMuse** [godspeedsystems/gs-node-service#582]
https://docs.godspeed.systems/docs/microservices/datasources/before-and-after-hooks

**Comment by arunsingh** [comment]
@xCodeMuse kindly add details/ context of the issue.

**Comment by mastersilv3r** [comment]
@sambamindgrep can you please here documentation of sample yaml for him to test.

**Comment by mastersilv3r** [comment]
Need to update the documentation

**Comment by mastersilv3r** [comment]
Its been implemented. Now Surya has to test and merge the PR into dev branch.

**Comment by mastersilv3r** [comment]
please create a section explaining with cross linking as appropriate.
