### ISSUE TITLE
creating elastricgraph model from PRISMA model

### ISSUE THREAD

**Issue by arunsingh** [godspeedsystems/gs-node-service#585]
provide command line and exact documentation

**Comment by mastersilv3r** [comment]
[] Create basic entities. 
[] Create relationships
[] Handle annotations
[] Create Elasticsearch.toml
[] Create joins/index.txt

**Comment by Srihari628** [comment]
- [ ] Create basic entities
- [ ] Create relationships
- [ ] Handle annotations 
- [ ] Create Elasticserach.toml
- [ ] Create joins/index.txt

**Comment by Srihari628** [comment]
I added a code to convert prisma schema to elastic graph schema..
added a elasticgraph.ts file which contain function to convert prisma schema to elasticgraph 
made some changes in index.ts like adding commands to the code 
also tested the code after making changes , it is working fine so i created a branch in the local repo and committed changes and raised a pr 
https://github.com/godspeedsystems/mindgrep-godspeed-cli/pull/2

**Comment by mastersilv3r** [comment]
please see comment in pull request , create another one with fix review with ashutosh where is the documentation of your command line?

**Comment by Srihari628** [comment]
#generate-elasticgraph-model

##You can convert the prisma schema into elasticgraph model by executing this commmand in your project root directory inside the dev container.

```
$ godspeed generate-elasticgraph-model
                      _                                   _ 
   __ _    ___     __| |  ___   _ __     ___    ___    __| |
  / _` |  / _ \   / _` | / __| | '_ \   / _ \  / _ \  / _` |
 | (_| | | (_) | | (_| | \__ \ | |_) | |  __/ |  __/ | (_| |
  \__, |  \___/   \__,_| |___/ | .__/   \___|  \___|  \__,_|
  |___/                        |_|                          
Usage: godspeed generate-elasticgraph-model [options] <egClientName>

Options:
  -m, --mysql <egClientName>     converts mysql prisma schema into eg-model
  -p, --postgres <egClientName>  converts postgres prisma schema into eg-model
  
```

**Comment by Mohit-Sharma1** [comment]
Type handling to be fixed for different kind of numbers bytes type json object type use custom.yaml where applicable

**Comment by Srihari628** [comment]
Type handling is done and trying to fix syntax errors and need to check by creating a godspeed project using eg

**Comment by Srihari628** [comment]
Type handling, syntax errors and creating custom.yaml is done.. Added few more tasks that need to be done.. working on them.. and for the added tasks im estimating the time of 12 hours..

**Comment by Srihari628** [comment]
Done with creating elasticMappings.json it took me 2hrs to do it..

**Comment by mastersilv3r** [comment]
Two points SriHri
A. Why are we giving options of mysql and postgres in CLI? It should be any
prisma file, for any db. We should just select a prisma file from those
found in his datasource folder if he just types gen eg model. Optionally
give him option for prisma file path, in case he wants to give any path on
his fs. Take that file and generate eg schema. Prisma supports 10
databases. A prisma file is independent of the underlying database so dont
tie this command to any database. Please study prisma database support and
enhance understanding of prisma. Please update the options in task spec and
share.
B. Is supporting of denormalization also done? We had discussed this part
as well. If not please add a task for next sprint

**Comment by Srihari628** [comment]
Yes sir i will make changes and will update the CLI accordingly.. And regarding denormalization the index.txt file in joins folder will be generated but user has to mention it in the prisma schema..

**Comment by Srihari628** [comment]
### generate-elasticgraph-model

**You can convert the prisma schema to elasticgraph model by executing this commmand in your project root directory inside the dev container.**

```
$ godspeed generate-elasticgraph-model
                      _                                   _ 
   __ _    ___     __| |  ___   _ __     ___    ___    __| |
  / _` |  / _ \   / _` | / __| | '_ \   / _ \  / _ \  / _` |
 | (_| | | (_) | | (_| | \__ \ | |_) | |  __/ |  __/ | (_| |
  \__, |  \___/   \__,_| |___/ | .__/   \___|  \___|  \__,_|
  |___/                        |_|                          
Usage: godspeed generate-elasticgraph-model [egClientName]
Enter the input path [default: ./generated-clients/postgres]: 
Enter the output path [default: ./src/datasources/eg_config]:

Elasticgraph model generated
```

:::note
- [egClientName] (optional): Specifies the name of the Elasticgraph client to be generated. If not provided, the default name `eg-model` will be used.
- If the specified input path does not exist, the CLI will display an error message.
- If the specified output path does not exist, the folder will be generated with [egClientName].
:::

**Comment by Srihari628** [comment]
added code to mindrep-godspeed-cli and raised a PR 
https://github.com/godspeedsystems/mindgrep-godspeed-cli/pull/3

**Comment by Srihari628** [comment]
added documentation and raised PR 
https://github.com/godspeedsystems/gs_doc/pull/43

**Comment by avtar-mindgrep** [comment]
enum is not getting generated properly to create indexing. Need to remove the enum part.

**Comment by Srihari628** [comment]
removed enum generating code and made changes accordingly to create all the required files.. and raised a PR
https://github.com/godspeedsystems/mindgrep-godspeed-cli/pull/4
