### ISSUE TITLE
tech spec of QA-integration env

### ISSUE THREAD

**Issue by arunsingh** [godspeedsystems/gs-node-service#592]

**Comment by arunsingh** [comment]
Avtar to share with the team how to spin up functional integration env,

**Comment by arunsingh** [comment]
@avtar-mindgrep to send the calendar invite to the Senior members of GS team.

**Comment by avtar-mindgrep** [comment]
[Document ](https://docs.google.com/document/d/1fsFmFsOstDKc6xvJqsKYFNVHiDOOe3gdEK3DIwWl6ZI/edit?usp=sharing)

**Comment by mastersilv3r** [comment]
To be reviewed byAyush

**Comment by mastersilv3r** [comment]
What is the process of ensuring documentation is in place? Can we add something in the goernance that the project manager also signs off documentation? 
Further, why not image scan in master merge? Shouldn’t trivy and sonarqube scans happen in all steps? @avtar-mindgrep @sambamindgrep

**Comment by avtar-mindgrep** [comment]
As for sonar and trivy scan, changes are done in dev only, we will just merge the changes from dev into master. Nothing new gets introduced in the master branch.
