### ISSUE TITLE
Completing elasticgraph in docusaurus.

### ISSUE THREAD

**Issue by arunsingh** [godspeedsystems/gs-node-service#594]
https://docs.godspeed.systems/docs/microservices/datasources/elasticgraph/

**Comment by mastersilv3r** [comment]
- [ ] Custom elasticsearch mapping
- [ ] AWS/Elasticsearch

**Comment by kushal-mindgrep** [comment]
Documentation completed. Please review the PR: https://github.com/godspeedsystems/gs_doc/pull/23
