### ISSUE TITLE
Request Body Limit Size

### ISSUE THREAD

**Issue by kushal-mindgrep** [godspeedsystems/gs-node-service#601]
Revert the request_body_limit changes from the master branch and first merge them into the dev branch

**In default.yaml**

**request_body_limit:** This variable sets the limit for the request body size. It checks if config.request_body_limit is defined in the application's configuration. If it is, the value from the configuration is used; otherwise, it defaults to 50 1024 1024 bytes (50 megabytes).

**file_size_limit:** This variable sets the limit for the file size. Similar to request_body_limit, it checks if config.file_size_limit is defined in the configuration. If it is, the value from the configuration is used; otherwise, it defaults to 50 1024 1024 bytes (50 megabytes).

https://docs.godspeed.systems/docs/microservices/setup/configuration/static-vars

**Comment by mastersilv3r** [comment]
@kushal-mindgrep what is the status of this?

**Comment by kushal-mindgrep** [comment]
@mastersilv3r I tested with the dev version, and everything is working fine. We can release this feature in the upcoming release.

**Comment by mastersilv3r** [comment]
This is a setting at config level.

**Comment by kushal-mindgrep** [comment]
@mastersilv3r @ashutoshmindgrep please review the PR: https://github.com/godspeedsystems/gs_doc/pull/22

**Comment by mastersilv3r** [comment]
@gnani please add how to reproduce
