### ISSUE TITLE
Testing RabbitMQ Integration

### ISSUE THREAD

**Issue by kushal-mindgrep** [godspeedsystems/gs-node-service#638]
@sambamindgrep  In the datasource, when I used

'loadFn: com.gs.rabbitmq.loader',

I encountered the following error:

Error: Cannot find module '../functions/com/gs/rabbitmq/loader'

To resolve this, I created a new 'loader.ts' file in the '/functions/com/gs' directory with

'loadFn: com.gs.loader' in the datasource configuration,
and the 'cannot find module' error was resolved.
However, I am now getting the following error:

Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'testQueue.rabbitMq' in vhost '/'"'

event and datasource files details given below:
Event File:

testQueue.rabbitmq:
id: rabbit_topic
fn: com.jfs.rabbit

Data Source File:

type: rabbitmq
config:
connectionString: amqp://guest:[guest@host.docker.internal](mailto:guest@host.docker.internal):5672
retryCount: 3
loadFn: com.gs.loader
executeFn: com.gs.rabbitmq.publish"

2. second error
TypeError: processEvent is not a function

**Comment by kushal-mindgrep** [comment]
https://github.com/godspeedsystems/gs-node-service/blob/feature-rabbitmq-webhook/src/functions/com/gs/rabbitmq.ts

**Comment by avtar-mindgrep** [comment]
For now not able to publish message in rabbitmq.
