### ISSUE TITLE
No generic response structure in id to id call, if we use existing response grammar fields, behaviour gets erratic[PL]

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#693]

**Comment by kushal-mindgrep** [comment]
xample:
		If an Id returns below response, it gets failed: (no wrapping in data node explicitly)
			{"success":true,"response":{"is_liveness_passed":true,"liveness_score":"0.7647"}}
		But if same id returns below response, it gets passed: (wrapping in data node)
			{"response":{"is_liveness_passed":true,"liveness_score":"0.7647"}}	
		success: true, false is needed for error handling
		The structure followed must be generic, you can't expect one response to be wrapped in data node, and other to be wrapped normally. And this is confusing while doing development.

**Comment by mastersilv3r** [comment]
Not enough information. Anyways, we have fixed return and transform in coming issue #978
