### ISSUE TITLE
Unclear logs for scripting error

### ISSUE THREAD

**Issue by shirisha-godspeed** [godspeedsystems/gs-node-service#795]
Getting unclear log message when the error occurred in a scripting no stack trace
![Screenshot from 2023-12-06 20-55-01](https://github.com/godspeedsystems/gs-node-service/assets/142990887/da6bccec-65a8-4e7c-9490-0b86e5f36a6a)

**Comment by siddarthvader** [comment]
@shirisha-godspeed this is in V1 or V2

**Comment by mastersilv3r** [comment]
Its coming with details now
