### ISSUE TITLE
Tracing: CLI changes

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#821]
Child task of #749 
**Add a new command in Godspeed CLI to enable OTEL in Godspeed.**

**Commands:** 
**`godspeed otel enable`**
It shall perform the below two tasks: 
- `npm i @godspeedsystems/tracing`
- Set OTEL_ENABLED=true in .env file of the Godspeed project.

**`godspeed otel disable`**
It shall perform the below two tasks:
- `npm uninstall @godspeedsystems/tracing`
- Set OTEL_ENABLED=false in .env file of the Godspeed project.

**Comment by gurjotkaur20** [comment]
Changes done in godspeed-cli
