### ISSUE TITLE
Error handling during service load time V2

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#864]
### The problem
Compilation issue always occur at runtime. They should happen at load time. Sometimes logs does not suggest the exact error cause, like line number, exact error etc.
Event validation on loadtime throw a proper error message with the file name for easy debugging.

### The solution

1. Both in events and workflows all YAML compile errors and as well inline JS compile errors should be highlighted during service load time, and process should exit with proper message including filename, and error part (apart from the IDE error highlighting during code=ing time as covered in issue #856 )

### How it will be solved
In both eventLoader.ts and functionLoader.ts follow proper checks and validations and ensure it works well. Follow all validations as discussed in #856 

### Cases covered:

    

- [x] Invalid Client [tested] http testing eventsorce 
- [x] Fn not present [tested] fn calling check 
- [x] Invalid Fn in case no function exist in the functions [tested] datsources
- [x] Validate Tasks of the workflow with workflow name [tested] 
- [ ] ID of the workflow [NOT YET, TO BE DISCUSSED]

**Comment by Mohit-Sharma1** [comment]
I test this out Invalid Client thing is not working means not giving an error why http reuest is failed at eventsource 
Fn not present its working dine 
 Invalid Fn in case no function exist in the functions, giving an error when i am chnageing the datasources 
 Validate Tasks of the workflow with workflow name - working fine

**Comment by mastersilv3r** [comment]
It is working now.
