### ISSUE TITLE
Support for godspeed create backend 

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#892]
## The Problem 

Create a Godspeed project in the current directory as currently it is making individual folder.  
## The Solution

Create a Godspeed cli like `godspeed create backend` it will make a files in the presenting project, not like a individual folder or project.  

## How will we solve

Need to change in the core and the have to add new CLI command for that.

## Test Cases

Currently we are woking in the test cases,  it will upload soon.

**Comment by mastersilv3r** [comment]
This is a possible approach when working in brownfield project. But its additional value is not very much. It seems simpler that a developer manually instantiate a godspeed project in their existing project, without much effort, by creating these folders himself. And instantiating Godspeed with the paths.
