### ISSUE TITLE
Option for User of- Case Type.

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#893]
## The Problem 

If user is working on Kebab Case and Godspeed supporting snake_case only. 

## The Solution

Create a Option for user that , the CLI should ask the user in which case user want to create a godspeed project

## How will we solve

Should be change in the Godspeed Core and make a change in the CLI. to create a command to as user to select a language (case type ) for the project.

## Test Cases

Currently working on test cases.

**Comment by mastersilv3r** [comment]
Godspeed is agnostic to cases used by developers. they can use kebab-case or camelCase or snake_case. currently we do not restrict how they name their files and variables. This can be a future piece maybe. closing it for now unless real use cases emerge.
