### ISSUE TITLE
config module is not able to read env variables from .env file

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#905]
## Version Information

@godspeedsystems/core package version: "2.2.3"

## Current Behavior
I have defined a custom environment variable in config/custom-environment-variables.yaml 
`f_token: F_TOKEN`

The env variable is set in the .env file in the project directory.
`F_TOKEN=/dev/F_AUTH_TOKEN`

When I am trying to access this variable in the workflow then it is not able to read from config. Below is the workflow:
![image](https://github.com/godspeedsystems/gs-node-service/assets/103424952/d639006a-e1eb-4fb6-8cb1-ff3eab2d9f96)

If I set the variable in the terminal using export command like `export F_TOKEN=/dev/F_AUTH_TOKEN` then it is working fine.

## Expected Behavior
config should read env variables from .env file also.

## Screenshot
![image](https://github.com/godspeedsystems/gs-node-service/assets/103424952/c02cb456-2f4f-46c8-bcc0-2b9c7f95897b)

**Comment by gurjotkaur20** [comment]
assign it to me

**Comment by mastersilv3r** [comment]
The solution is this
In your godspeed project's package.json add change two commands to include mappings, plugins and configs to be copied from src to dist, and also to be watched 

```
"build": "swc src -d dist && rsync -a --exclude '*.ts' ./src/ ./dist/ && rsync -a --exclude '*.ts' ./mappings/ ./dist/mappings && rsync -a --exclude '*.ts' ./config/ ./dist/config",
"serve": "nodemon --watch src --watch config --watch mappings --watch plugins -e ts,js,yaml,json,.env --exec 'npm run build && npm run preview'",
```

**Comment by gurjotkaur20** [comment]
> The solution is this In your godspeed project's package.json add change two commands to include mappings, plugins and configs to be copied from src to dist, and also to be watched
> 
> ```
> "build": "swc src -d dist && rsync -a --exclude '*.ts' ./src/ ./dist/ && rsync -a --exclude '*.ts' ./mappings/ ./dist/mappings && rsync -a --exclude '*.ts' ./config/ ./dist/config",
> "serve": "nodemon --watch src --watch config --watch mappings --watch plugins -e ts,js,yaml,json,.env --exec 'npm run build && npm run preview'",
> ```

I guess there is a small issue in the build command. mappings folder will be inside src, so `./src/mappings/` should be mentioned.
