### ISSUE TITLE
Project Scaffolding Issues

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-node-service#907]
[PR number 12](https://github.com/godspeedsystems/godspeed-scaffolding/pull/13) in scaffolding project

## The Problem 
There are a bunch of small issues in new projects created via godspeed create command.
## The Solution

- [x] Don't add .devcotnainer file from new Godspeed project
- [x] Add eslintrc in new godspeed projects (same as the one in gs-node-service)
- [x] Create config folder with default.yaml and custom-environment-variables.yaml. 

```yaml
 # default.yaml
 log_level: debug
 lang: coffee #js You can set either coffee or js as your inline scripting language
 redact: ['a.b.c', 'a.b.*', 'req.headers'] #refer pino log redact features to know more about log redaction
``` 

```yaml
# custom-environment-variables.yaml
node_env: NODE_ENV #where NODE_ENV is an environment variable set by you. This will be accessible as config.node_env in inline script and ctx.config.node_env in JS/TS
```
- [x] Create mappings folder with empty index.yaml
- [x] Create plugins folder with sample.js (plugins to only support js for now. Add this to the documentation)

- [x] Change build command 
``` "build": swc src -d dist && rsync -a --exclude '*.ts' ./src/ ./dist/ && rsync -a ./config/ ./dist/config && rsync -a ./src/mappings/ ./dist/mappings && rsync -a ./src/plugins/ ./dist/plugins && node ./node_modules/@godspeedsystems/core/dist/core/transpiler.js```

- [x] JSON schema of events in new project is wrong. No `content` is there in body. Fix the JSON schema of generated events.
- [x] "serve": "nodemon --watch src --watch config --watch mappings --watch plugins -e ts,js,yaml,json,.env --exec 'npm run build && npm run preview'",
- [x] Remove dependency of godspeed modules and plugins from `latest` to the actually installed version of Godspeed in project's package.json. For example, if dev has installed godspeed V2.2.4 then get the versions of his installed godspeed core etc. and add those in package.json. 
```json
"@godspeedsystems/api-generator": "latest", //this should be exact version
"@godspeedsystems/core": "latest", //exact version
"@godspeedsystems/plugins-aws-as-datasource": "^1.0.1",
"@godspeedsystems/plugins-axios-as-datasource": "latest", ////exact version to be added when adding plugin
"@godspeedsystems/plugins-express-as-http": "latest", //exact version to be added when adding plugin
```
- [x] P2: When creating project, examples must come from an examples or templates mono-repo.

---- For Debugger setup ----

- [x] To make sourcemap of ts workflows update gs project template .swcrc file and add a line `"sourceMaps": true` for debugging typescript files

- [x] Make an env file and set GS_TRANSPILE=true for enabling transpiling of yaml to js with sourcemap

- [x] create a file in .vscode folder "launch.json" filename
```
{
 
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "smartStep": true,
            "stopOnEntry": false,
            "cwd": "${workspaceFolder}/src",
            "program": "index.ts",
            "env": {
                "GS_TRANSPILE": "true"
            },
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }
    ]
}
```

- [x] "debug.allowBreakpointsEverywhere": true set this in settings.json of .vscode folder

-----Debugger setup-----

## How will we solve
Godspeed's CLI will need to be changed for this
In case the feature of plugins breaks anything. Remove that for now. We will handle later

## Test Cases
To be written

**Comment by gurjotkaur20** [comment]
- build command: mappings and plugins folder path should be changes to ./src/mappings and ./src/plugins.
- similar change in serve command.

**Comment by mastersilv3r** [comment]
@xCodeMuse what is the status of this issue?

**Comment by mastersilv3r** [comment]
@xCodeMuse Today three issues are still remaining
Please check the unticked boxes. configs and mappings need to be inside the src folder not outside. Marking this as a bug.
