### ISSUE TITLE
/metrics is not working in project created using Godspeed version v2

### ISSUE THREAD

**Issue by avtar-mindgrep** [godspeedsystems/gs-node-service#922]
## Version Information

@godspeedsystes/ore: 2.3.0

## Current Behavior
/metrics endpoint is not working and service is crashing.

## Expected Behavior
It should give app metrics when /metrics is triggered.

## Screenshots or Screencast
![gs-node-issue-1](https://github.com/godspeedsystems/gs-node-service/assets/95289348/a7157c9c-f106-4742-82c6-aa20d7a07014)
![gs-node-issue-2](https://github.com/godspeedsystems/gs-node-service/assets/95289348/3ba29e4a-f55a-4f6d-b5e9-ef304e587bef)

**Comment by gurjotkaur20** [comment]
Let me check it.
