### ISSUE TITLE
Unable to Call Dynamic Datasource

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#946]
### Encountering an issue where it's not possible to call a dynamic datasource. Attempted to use the following format:

```yaml

 fn: <js% `datasource.api.get.${config.api_end_point}`%>
```
##
Whereas, Calling thse two types of functions is working properly:
```yaml
fn: |
  <js% 
    return 'com.gs.return'
  %>
```
```yaml

fn: |
  <js% 
    return 'test'
  %>


```

**Comment by mastersilv3r** [comment]
duplicate
